version: '3.7'
services:
    client:
        container_name: poke-react-client
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development
        stdin_open: true

    server:
        container_name: poke-react-server
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '8081:8080'
        environment:
            - NODE_ENV=development
        stdin_open: true