version: '3.7'
services:
    ssr:
        
        container_name: poke-react-ssr
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
            - '/app/.next'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
        stdin_open: true